#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Aug 17 13:43:04 2023

@author: mahjoubp
"""

import numpy as np
import subprocess
import sys ,os ,time, shutil

#KS

#function def -----------------------------------------------------------------

#classic

def getOA():
    
    opt = []
    arg = []
    
    for aIn in sys.argv :
        
        if aIn != sys.argv[0] :
            if aIn[0] == '-' :
                opt.append(aIn)
            
            else :
                arg.append(aIn)
        
    return opt, arg



#personnalised

def pHelp() :
    print( "\033[90m############################################################\033[0m" )
    print( "                          \033[1m\033[4mlns HELP\033[0m" )
    print( "\033[90m############################################################\033[0m" )
    print( "" )
    print( "lns command launch command in an other 'screen' and open it in a new terminal." )
    print( "" )
    print( "Requierement : " )
    print( "	> have 'screen' installed" )
    print( "	> have 'Konsole' installed" )
    print( "	(> if it is used on a server, be connected in ssh -X (graphic options))" )
    print( "" )
    print( "\033[1mSyntaxe :\033[0m \033[94mlns\033[0m [\033[94m-options\033[0m] \033[94mcmd\033[0m [\033[94mscreen_name\033[0m]" )
    print( "" )
    print( "\033[1mOptions :\033[0m " )
    print( "	\033[94m-h\033[0m	display this message" )
    print( "	\033[94m-c\033[0m	close screen after execution" )
    print( "" )
    print( "" )
    print( "\033[90m############################################################\033[0m" )
        
    
def wrn() :
     print( "\033[5m\033[1m\033[93m<!>\033[0m\033[25m" , end='')
          
             
     
# MAIN ------------------------------------------------------------------------


#options
opts, args = getOA()

for o in opts :
    
    if o == '-h' :
        pHelp()


#Init var
exist = True
num = 1
cmd = ''
nd = False
rnd = False


#if no screen name is provided
if len(args) == 0 :
    wrn()
    print(' No screen name provided !' )


else :
    
    screen_name = args[0]
    
    exist = bool(int(subprocess.getoutput("ison -e " + screen_name)))
    
    #if already exist rename
    if not exist :
        wrn()
        print(' ' + screen_name + ' screen does not exist !')
        
    #kill process
    else :
        sid = subprocess.getoutput("ison -n " + screen_name)
        os.system( 'kill ' + str(sid) )


    
    
    

        
