#!/bin/bash

############################################################
#Function                                                  #
############################################################

#Help

Help()
{
printf "\033[90m############################################################\033[0m\n"
printf "                          \033[1m\033[4mlpys HELP\033[0m\n"
printf "\033[90m############################################################\033[0m\n"
printf "\n"
printf "lpys command launch python script in an other 'screen' and open it in a new terminal.\n"
printf "\n"
printf "Requierement : \n"
printf "	> have 'screen' installed\n"
printf "	> have 'Konsole' installed\n"
printf "	(> if it is used on a server, be connected in ssh -X (graphic options))\n"
printf "\n"
printf "\033[1mSyntaxe :\033[0m \033[94mlpys\033[0m [\033[94m-options\033[0m] \033[94mfile.py\033[0m [\033[94mscreen_name\033[0m]\n"
printf "\n"
printf "\033[1mOptions :\033[0m \n"
printf "	\033[94m-s\033[0m	solo threaded\n"
printf "	\033[94m-m\033[0m	multi threaded\n"
printf "	\033[94m-n\033[0m [\033[94mnumber_of_thread\033[0m] allows number of threads\n"
printf "	\033[94m-i\033[0m	let user interact user with python shell after execution\n"
printf "\n"
printf "\033[90m############################################################\033[0m\n"
}

############################################################
#Main                                                      #
############################################################

#def var

co=1
flag=''
pyop=''

#get options

while getopts ":hsmni:" option;
do
	case $option in
	
      		h) # display Help
         		Help
			((co++))
         		exit;;
         		
         	s)
         		tc='set'
			nt=1
			((co++))
			;;
			
		m)
			tc='m'
			nt=$(nproc)
			((co++))
			;;
			
		n)
			tc='set'
			nt=$(($co))
			flag='nt'
			co=$(($co + 2))
			;;
			
		i)
			pyop='-i'
			((co++))
			;;
				
         	\?) # Invalid option
         		echo "Error: Invalid option"
         		exit;;
   	esac
done


#manage pointer
name=$(($co))
p_s_name=$(($co + 1))
s_name=${!p_s_name}

rfpath=$(realpath -e ${!name})
if [[ ${#s_name} == 0 ]]; then
	s_name=${!name}
fi

#set simu with $nt core
if [[ "$tc" == "s" ]] || [[ "$tc" == 'set' ]];
then
	set -o xtrace
	export OPENBLAS_NUM_THREADS=$nt
	export OMP_NUM_THREADS=$nt
fi


#launch in screen and open new term
screen -dmS $s_name bash -c "python3 $pyop '$rfpath'; exit;"
konsole -e bash -c "screen -r $s_name" & disown
